### ISSUE TITLE
Convert.toInt in GPXTrack.swift

### ISSUE THREAD

**Issue by coolcooldool** [vincentneo/CoreGPX#33]
I am sorry, It is maybe a very simple problem.

When I compile an error occured at line 53,
"Use of unresolved identifier 'Convert'; "
①Where is the Convert class?

so, I replace the code
```self.number = Convert.toInt(from: dictionary["number"])```
with
```self.number = integer(from: dictionary["number"])```
②is that ok?

Thanks!

**Comment by vincentneo** [comment]
Hello @coolcooldool ,

the `Convert` class was added not too long ago, and the integer(from:) method has since been removed, to declutter the code. The `Convert` class is located in `Converters.swift` file.

Have you updated to the latest commit?

Thank you!

**Comment by coolcooldool** [comment]
Hello @vincentneo 

Thank you for your response.
I used the framework with another app project,
maybe update when this framework is changing,
so cause the problem.
I clone the project again and pod update one more time,
This problem is fixed.
Thanks for this good GPX framework!

Thank you!

**Comment by vincentneo** [comment]
Great to hear that the problem is resolved!
Thanks for the support, too!

Have a great day!
