### ISSUE TITLE
Declutter/Revamp GPXParser

### ISSUE THREAD

**Issue by vincentneo** [vincentneo/CoreGPX#39]
`GPXParser` looks absolutely like a mess right now, and will get worse once `GPXExtensions` features are fully implemented.

Something must be taken to optimize the lengthy code.

**Comment by stagedataloss** [comment]
test123

**Comment by vincentneo** [comment]
Work will be done on branch [refactor/GPXParser](https://github.com/vincentneo/CoreGPX/tree/refactor/GPXParser).
