### ISSUE TITLE
Incorrect String format in GPXBounds

### ISSUE THREAD

**Issue by INDAPP** [vincentneo/CoreGPX#40]
3 arguments required, but only one specified.
Insert get tagName and attribute

https://github.com/vincentneo/CoreGPX/blob/49646feeb9b7a12db848b30c2712bf772b0265fa/Classes/GPXBounds.swift#L89

**Comment by vincentneo** [comment]
Oh no! Glad that you noticed and informed! Must have been my utter neglect toward GPXBounds resulting this.
Will get it fixed tomorrow! 

Thank you!
