### ISSUE TITLE
Errors on converting to Swift 5.0

### ISSUE THREAD

**Issue by jdleung** [vincentneo/CoreGPX#41]
I got following errors when I tried to convert the project to Swift 5.0, how to fix them? Thanks

> module map file 'build/Release-iphoneos/CoreGPX/CoreGPX.modulemap' not found

> Cannot load underlying module for 'CoreGPX'

**Comment by vincentneo** [comment]
Does the older pull request #34 work? Last remembered the pull request to be working, though its outdated now.

The whole project will be going Swift 5 soon.

**Comment by vincentneo** [comment]
I have checked that the contents of #34 is still valid, as the project did not require any code changes, except for the project migration stuff to swift 5. As I have said earlier, #34 will be merged to master soon.

**Comment by jdleung** [comment]
I had tried to clean and delete derived data, not work.
OK, I prefer to wait for the new version with Swift 5.
Thanks.

**Comment by vincentneo** [comment]
@jdleung,

The project has now been updated for Swift 5 from version 0.6.5.
Please update your pods to use this new version. Will close this for now, as my personal testing showed that it worked.

Thank you!

**Comment by jdleung** [comment]
CoreGPX has been updated to 0.6.5, the project still can run without error, but the errors still exist when converting to Swift 5.0.

> <unknown>:0: error: module map file 'build/Release-iphoneos/CoreGPX/CoreGPX.modulemap' not found
> <unknown>:0: error: module map file 'build/Release-iphoneos/CoreGPX/CoreGPX.modulemap' not found
> <unknown>:0: error: missing required module 'SwiftShims'

**Comment by vincentneo** [comment]
@jdleung May I ask what cocoa pods version do you have?

**Comment by jdleung** [comment]
Sorry for delay,

My CocoaPods version is 1.6.1.

Though CoreGPX 0.6.5 is already Swift 5, but when Xcode reminds me to update to Swift 5,  `libCoreGPX.a` is included. Errors still exist even I uncheck it.

**Comment by vincentneo** [comment]
You should try and update your CocoaPods version. I remember that v1.7.4 is the latest release, and is more suited for >Xcode 10.2 (swift 5.)

After which, run pod update again to see if issue persists.

**Comment by jdleung** [comment]
Problem exists after update CocoaPods to latest version.

Tried to manually set swift version from 4.2 to 5.0 in all targets, warning disappears and the App runs well but it's an abnormal way. Just a test.

**Comment by vincentneo** [comment]
Hi 
 
May I ask what abnormal behaviour was observed? Maybe it’s a bug that I didn’t know of. 

Also, do always clean project after a pod update. Sometimes not doing that can have abnormal results as well.

Thank you!

**Comment by jdleung** [comment]
It's the best way to let Xcode convert code from 4.2 to 5.0, otherwise it may cause unknown problem, I think, if I manually(abnormally) only set the Swift version to 5.0.

Project cleaned, Derived Data deleted, CoreGPX uninstalled and installed again for times ;-(

Actually, The App is working well with Swift 4.2 and those warnings, but somehow just want to remove those bright yellow warnings.

**Comment by vincentneo** [comment]
Is it possible for you to screenshot the list of warnings? Or is it that the warning is the modulemap one? Really wish to iron any remaining bugs out.

**Comment by jdleung** [comment]
Here is the screenshot, Thanks.
![ 2019-07-13](https://user-images.githubusercontent.com/486474/61170479-2d008200-a59c-11e9-820e-9b4869709ab0.png)

**Comment by vincentneo** [comment]
I'll try to replicate this issue when free. 
For now, I am unable to replicate this weird bug. I will try to use a pre-Swift 5 project for testing to convert.

Apologies that you have to deal with this for now.

**Comment by jdleung** [comment]
Thank you.

**Comment by vincentneo** [comment]
May I ask, if you can find ‎⁨ **-INSERT YOUR PROJECT FOLDER-**/⁨Pods⁩/Target Support Files⁩/⁨CoreGPX-iOS⁩/CoreGPX-iOS.modulemap ?

**Comment by jdleung** [comment]
There is a `CoreGPX/CoreGPX-iOS.moduleMap` in my project Pods, no such folder `CoreGPX-iOS`.

**Comment by vincentneo** [comment]
Yeah that looks like acceptable behaviour of the pods. (I think its called CoreGPX, instead of CoreGPX-iOS due to this being an iOS-only app, am I right?)

Interesting how there is a modulemap there but, not when building in the build directory.

Will continue to research on this, though still inconclusive as of yet.

**Comment by jdleung** [comment]
Sorry, not iOS-only App, it's been updated to support WatchOS in the new version. Is something wrong with WatchOS? But on Apple Watch, App doesn't use CoreGPX, all data must be transfered to iPhone first if users need to share GPX files.

**Comment by vincentneo** [comment]
In that case, if CoreGPX lib is only for the iOS app, I would assume that the folder would still be created as CoreGPX, as there is not need for preventing conflicts.

Interesting issue that has lead to no observable, conclusive answer. Will research further.

**Comment by vincentneo** [comment]
Thought of an idea.

Have you tried cloning the example CoreGPX app, from here? If the example app works, that should mean that there is something wrong with your personal project file configuration, as the "known working" example app, works, but not your personal project.

If the example app doesn't work, then there is probably something wrong on my side, probably something wrong with the podspec or something.

This should get us somewhere closer to a conclusion of the issue.

**Comment by jdleung** [comment]
OK, I'll take a try on a fresh new project later. Thanks.

**Comment by vincentneo** [comment]
@jdleung,
Hello, any updates? Did it work?
I still failed to replicate your issue, during the past week. Wondering if you found a solution?

Thank you!

**Comment by jdleung** [comment]
Sorry, my Xcode has been updated to the latest version, new project will be created with Swift 5, I think I cannot replicate another one too.

**Comment by jdleung** [comment]
I found `coreGPX.modulemap` reference in 3 places(both in `Pods-myProject.debug.xcconfig` and `Pods-myProject.release.xcconfig):
1. OTHER_CFLAGS = $(inherited) -fmodule-map-file="${PODS_CONFIGURATION_BUILD_DIR}/CoreGPX/CoreGPX.modulemap"
2. OTHER_SWIFT_FLAGS = $(inherited) -D COCOAPODS -Xcc -fmodule-map-file="${PODS_CONFIGURATION_BUILD_DIR}/CoreGPX/CoreGPX.modulemap"
3. Targets > CoreGPX > Build Settings > Module Map File

**Comment by vincentneo** [comment]
Can you test a new Swift 5 project with this pod installed? 

Other than that, the CoreGPX.modulemap references seems consistent? I mean they look like they belong there.

**Comment by jdleung** [comment]
I did it, but the new project works well since it's created with Swift 5.

Then I tried to set it back to Swift 4.2 in Targets > Build Settings > Swift compiler - Language > Swift Version, Xcode showed up a warning `Conversion to Swift 5 is available`. Clicked and selected `Next` to convert, the errors came out. 

`**Convert to Current Swift Syntax Failed**`
`Please ensure that all selected targets build successfully with the currently configured Swift version before attempting a migration.`

My old project did not handle like the above, it's original Swift 4.2.

**Comment by vincentneo** [comment]
Is it possible for you to backup the problematic project, and then try and remove Cocoapods stuff from the project, and to reinstall back all your pods, after that?

In this case, a backup / proper git setup is important, in case something goes wrong along the way.

Information about CocoaPods removal can be found here: https://stackoverflow.com/questions/16427421/how-to-remove-cocoapods-from-a-project

**Comment by jdleung** [comment]
I think it will make no difference, the new project was originally created without any Cocoapods stuff, after then installed CoreGPX only. 

You can try it yourself:
1. Create a new project
2. Install CoreGPX
3. Set Swift version to 4.2
3. Update to Swift 5

**Comment by vincentneo** [comment]
Alright, will try to test again in the coming weeks.

**Comment by vincentneo** [comment]
I tried to replicate with the four steps, but failed to get any errors, by converting to Swift 5.

I changed `SWIFT_VERSION` in `project.pbxproj` from 5.0 to 4.2, and the Xcode Conversion to Swift 5 prompt completed without syntax changes.

I was using Xcode 10.2.1 and latest git master branch of CoreGPX (pre-released 0.7.0), by the way.

Ugh, this issue gets more confusing.

**Comment by jdleung** [comment]
Set SWIFT_VERSION to 4.2 in Target, not project.

**Comment by vincentneo** [comment]
> Set SWIFT_VERSION to 4.2 in Target, not project.

When I do that, the Xcode Conversion to Swift 5 prompt completed without syntax changes, again. Further more, the update is available kind of a message warning doesn't even appear.

**Comment by jdleung** [comment]
OK, it may be the problem of my side, I have to choose to ignore it until it fails to work.

**Comment by vincentneo** [comment]
Alright. Any updates just reopen this and post it here, ok?
Maybe one day we can sort this out.

Thanks for using this project anyways!

**Comment by jdleung** [comment]
New report: Just upgraded Xcode to version 11.0, and converted the project to Swift 5 without any error.

**Comment by vincentneo** [comment]
Thats good to hear! 
Thanks for the update, and have a great day ahead!
