### ISSUE TITLE
Support GPX 1.0 standards

### ISSUE THREAD

**Issue by vincentneo** [vincentneo/CoreGPX#51]
I believe it would be good to support GPX 1.0 files as well, other than just the GPX 1.1 standard. The goal is to have `GPXParser` auto detect version via `version` attribute defined in the gpx header.

**Comment by georgbachmann** [comment]
+1 This would be great!!!

**Comment by vincentneo** [comment]
Wow I just noticed the response from this.

Surely this would be one priority for this project now.

**Comment by vincentneo** [comment]
I was researching about v1 differences when I chanced upon that there was actually schemas on their website for GPX v0.4, v0.5, v0.6 and v1.2...

I didn't know that GPX had a v1.2. Not much difference though, mostly just to highlight a version change and a `strict` rule on one of the tags, probably suggesting that it was cancelled.
