### ISSUE TITLE
Compact GPX file

### ISSUE THREAD

**Issue by jearle1974** [vincentneo/CoreGPX#56]
Would love to see a feature to compact a large gpx file. I have a file with over 23000 track points that crashes due to memory everything I try to overlay it on MKMAPVIEW. Would be great to be able to import the file and then reduce the number of track points without altering the track too much.

**Comment by vincentneo** [comment]
Hi @jearle1974,

Sorry, but I don't quite understand what you are requesting right now?

I interpreted as either three:
- To only load to a certain extent of track points, for example, first 10000 points
- To strip duplicated or 'near by' points as the file parses
- To remove random points in the gpx file as when parsing, reducing track's accuracy, but improving performance


Do update me on what you wish to have, in either the three listed above, or something else if I interpreted it wrongly.

Thanks for using the project anyways! :)

**Comment by jearle1974** [comment]
Number 3 was what I was asking, but number 2 is nice as well. Are either of these possible currently?

To strip duplicated or 'near by' points as the file parses

To remove random points in the gpx file as when parsing, reducing track's accuracy, but improving performance

**Comment by vincentneo** [comment]
@jearle1974 Both are possible, I think.

For the 2nd idea, i think it would work out by having a radius to remove, e.g 200m to remove/skip
For the 3rd idea, I think it will work through random function in `Int`

Once I have the free time, I will work on it!

**Comment by jearle1974** [comment]
Wow, thanks! That would be an awesome addition

**Comment by vincentneo** [comment]
Work will be done on this [branch](https://github.com/vincentneo/CoreGPX/tree/enhancements/56).

Will be done as and when time permits!

**Comment by lludo** [comment]
@jearle1974 It sounds like this feature is not really the job of a GPX parsing library but the use you make of it on your app side, no?

**Comment by vincentneo** [comment]
@lludo, technically, you are right, as I believe it can be done on the personal app side.
That said, I do feel that this may hold value for future and current users, should they want similar functionality, which made me want to try an implementation. 

It won't arrive soon though, as I have other (more important, personal) things to do.

**Comment by jearle1974** [comment]
> @jearle1974 It sounds like this feature is not really the job of a GPX parsing library but the use you make of it on your app side, no?

You are absolutely right this can be done on the app side, I was just thinking it would be a nice feature to eliminate having to do it on the app side and to add another nice feature to the already awesome work you all have done. Much appreciate all your efforts.
