### ISSUE TITLE
Swift Package manager does not work due to duplicate class found

### ISSUE THREAD

**Issue by lludo** [vincentneo/CoreGPX#57]
```
<unknown>:0: error: filename "GPXParser.swift" used twice: '/Users/ludovic/Library/Developer/Xcode/DerivedData/Quantified-ciiclhkulrdksfatkpwrnpzveqbt/SourcePackages/checkouts/CoreGPX/Classes/Archived/GPXParser.swift' and '/Users/ludovic/Library/Developer/Xcode/DerivedData/Quantified-ciiclhkulrdksfatkpwrnpzveqbt/SourcePackages/checkouts/CoreGPX/Classes/GPXParser.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
Command CompileSwiftSources failed with a nonzero exit code
```

<img width="1277" alt="Screen Shot 2019-10-21 at 8 42 28 PM" src="https://user-images.githubusercontent.com/631630/67258008-80a82480-f443-11e9-81ae-e5794ea82731.png">

**Comment by lludo** [comment]
Looks like the `Archived` folder should be removed or excluded from SPM?

**Comment by vincentneo** [comment]
@lludo , I will remove Archived folder since it no longer holds much value. 

Thanks for notifying about this!

**Comment by edorphy** [comment]
> @lludo , I will remove Archived folder since it no longer holds much value.
> 
> Thanks for notifying about this!

Will this be in a release soon? First time exploring Swift Package Manager in Xcode 11. I see there is an option to specify a commit, but it would be much cleaner if it was in the normal releases. :)

**Comment by vincentneo** [comment]
@edorphy,
So sorry! I didn't know much about the package manager, and the fact that it lists via versions just like CocoaPods.

Will make a new release after I type this!

**Comment by vincentneo** [comment]
Alright! Release 0.7.2 is out!

**Comment by edorphy** [comment]
@vincentneo Thanks!
