### ISSUE TITLE
Keep receiving an error with watchOS

### ISSUE THREAD

**Issue by jearle1974** [vincentneo/CoreGPX#68]
I keep getting an error when I try to run my watchOS application. Am I doing something wrong. I have included it with both my app NLTrails and the NLT-Watch Extension. Here is what I get, I have tried restarting all devices and clean folder with no luck.

dyld: Library not loaded: @rpath/CoreGPX.framework/CoreGPX
  Referenced from: /private/var/containers/Bundle/Application/5AA2A27C-D83A-43CE-8822-514304A0DC40/NLT-Watch.app/PlugIns/NLT-Watch Extension.appex/NLT-Watch Extension
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/5AA2A27C-D83A-43CE-8822-514304A0DC40/NLT-Watch.app/PlugIns/NLT-Watch Extension.appex/Frameworks/CoreGPX.framework/CoreGPX: code signature invalid for '/private/var/containers/Bundle/Application/5AA2A27C-D83A-43CE-8822-514304A0DC40/NLT-Watch.app/PlugIns/NLT-Watch Extension.appex/Frameworks/CoreGPX.framework/CoreGPX'

	/private/var/containers/Bundle/Application/5AA2A27C-D83A-43CE-8822-514304A0DC40/NLT-Watch.app/PlugIns/NLT-Watch Extension.appex/Frameworks/CoreGPX.framework/CoreGPX: stat() failed with errno=1
	/private/var/containers/Bundle/Application/5AA2A27C-D83A-43CE-8822-514304A0DC40/NLT-Watch.app/PlugIns/NLT-Watch Extension.appex/Frameworks/CoreGPX.framework/CoreGPX: code signature invalid for '/private/var/containers/Bundle/Application/5AA2A27C-D83A-43CE-8822-514304A0DC40/NLT-Watch.app/PlugIns/NLT-Watch Extension.appex/Frameworks/CoreGPX.framework/CoreGPX'

	/private/var/containers/Bundle/Application/5AA2A27C-D83A-43CE-8822-514304A0DC40/NLT-Watch.app/PlugIns/NLT-Watch Extension.appex/Frameworks/CoreGPX.framework/CoreGPX: stat() failed with errno=1
	/private/var/containers/Bundle/Application/5AA2A27C-D83A-43CE-8822-514304A0DC40/NLT-Watch.app/PlugIns/NLT-Watch Extension.appex/Frameworks/CoreGPX.framework/CoreGPX: code signature invalid for '/private/var/containers/Bundle/Application/5AA2A27C-D83A-43CE-8822-514304A0DC40/NLT-Watch.app/PlugIns/NLT-Watch Extension.appex/Frameworks/CoreGPX.framework/CoreGPX'

	/private/var/containers/Bundle/Application/5AA2A27C-D83A-43CE-8822-514304A0DC40/NLT-Watch.app/PlugIns/NLT-Watch Extension.appex/Frameworks/CoreGPX.framework/CoreGPX: stat() failed with errno=1

**Comment by vincentneo** [comment]
Hi @jearle1974,

Are you using CocoaPods or Swift Package Manager?

If it's CocoaPods, I suggest that you update it, as that can sometimes cause issues. 
That said, googling seem to show quite a number of similar issues. 
Do see if some of these helps:
https://github.com/Alamofire/Alamofire/issues/101
https://github.com/CocoaPods/CocoaPods/issues/8664

As for SPM, I did personally encounter an issue for using CoreGPX under watchOS.

**Comment by jearle1974** [comment]
Using CocoaPods and have the latest version except for the beta just released. I will check the parts you shared to see if I can find a solution.

**Comment by jearle1974** [comment]
I've tried everything. I cannot figure out how to get this to work. Just not making any sense to me, I must be missing something.

**Comment by vincentneo** [comment]
How about trying this: remove CoreGPX in the pod file, then run pod install. After that, add it back in the podfile, then run pod install again?

Maybe that would clean up cocoapods in some way or form.

**Comment by jearle1974** [comment]
> How about trying this: remove CoreGPX in the pod file, then run pod install. After that, add it back in the podfile, then run pod install again?
> 
> Maybe that would clean up cocoapods in some way or form.

I tried without success. I even uninstalled cocoapods and reinstalled. Still getting the same error. Wondering if it has something to do with the other pods I am using. I will keep trying :( Very frustrating why Xcode is doing this. I cloned iOS-Open-GPX-Tracker and ran it fine from Xcode, but I can not get it to work in my own project.

**Comment by vincentneo** [comment]
Very weird indeed. Maybe you should try to switch, to say SPM, once I get it settled (as watchOS support for this lib seems broken)

**Comment by jearle1974** [comment]
> Very weird indeed. Maybe you should try to switch, to say SPM, once I get it settled (as watchOS support for this lib seems broken)

Must be something I am missing. I just added all the pods I am using to the iOS-Open-GPX-Tracker and ran it and everything works. Not sure why it won't work in mine but I will have to keep looking.

**Comment by jearle1974** [comment]
Finally figured it out. It was all to do with human error. I renamed / recreated my watch extension at one point early on and missed something in the conversion. After renewing my developer license with apple and running on my iPhone I was able to see the error and upon searching my project located the old reference error.

**Comment by vincentneo** [comment]
That's good to know!
