### ISSUE TITLE
MetaData Nil

### ISSUE THREAD

**Issue by jearle1974** [vincentneo/CoreGPX#69]
After creating and saving a GPX file with MetaData and verifying via print that the file does have the MetaData Tags, upon opening the file and converting via

guard let gpx = GPXParser(withURL: curFile)?.parsedData() else { completion(false); return; }
let rideType = gpx.metadata?.keyword

the rideType as well as any other MetaData show nil.

Do you have documentation on how to properly use the MetaData?

Thank you in advance.
Jason

**Comment by vincentneo** [comment]
Hi @jearle1974 again,

Interesting encounter... I have tested with my personal private project and on my end, it seems like it seems to be working as expected?

Judging from your two lines, it seems like you are already 'properly' using the metadata.

So, a few questions to ask:
- is `gpx.metadata` itself `nil`?
- was the file generated from CoreGPX?
- if it was generated from CoreGPX, can you check if the file's metadata is 'rendered' correctly? (i.e. wrong tag name attributes?)

As for your #56/#63 issue, sorry for the delays, but you can expect it to be merged soon, once I double check and confirm its working, etc.

**Comment by jearle1974** [comment]
yes the gpx.metadata itself is nil upon opening the file
yes file was generated from CoreGPX
It looks ok, after saving the file I ran the print root.gpx() and this was the result, I do not have any tracks or track segments as it was only a quick test inside without GPS. I will try adding a location file to see if I get same results.

> <?xml version="1.0" encoding="UTF-8"?>
> 
> <gpx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" version="1.1" creator="NL Trail Riders">
> 
> 	<metadata>
> 
> 		<time>2020-01-06T11:32:49Z</time>
> 
> 		<keyword>ATV</keyword>
> 
> 	</metadata>
> 
> 	<trk>
> 
> 		<trkseg>
> 
> 		</trkseg>
> 
> 	</trk>
> 
> </gpx>

However after I open the file the metadata is nil as per the attached image

![Screen Shot 2020-01-06 at 8 03 46 AM](https://user-images.githubusercontent.com/56170634/71815933-9a790100-305b-11ea-9f32-f0e3ccc484ae.png)

**Comment by jearle1974** [comment]
Even when adding location file and producing tracks and segments with my file I receive the same error. Any thoughts?

![Screen Shot 2020-01-06 at 8 19 50 AM](https://user-images.githubusercontent.com/56170634/71816533-761e2400-305d-11ea-9302-08651f9e32cb.png)

**Comment by vincentneo** [comment]
I’ll scrutinised my code again tomorrow. 
Apologies for having buggy code in this project...

**Comment by jearle1974** [comment]
Ok, thanks for removing :) 

I would not classify your code as buggy by no means, it is great! I just seem to be having this small issue. It could be on my side...lol

**Comment by jearle1974** [comment]
I decided to try adding metadata info in Merlos iOS-Open-GPX-Tracker as well just to test. Upon reopening the file I did receive metadata as nil, same result as noted above.

**Comment by vincentneo** [comment]
Hi @jearle1974,

Can you try out #70? In my testings it appears to work fine. Thank you.

**Comment by jearle1974** [comment]
Works perfect Vincent, thanks for the fix!

**Comment by vincentneo** [comment]
good to know! will merge #70!
