### ISSUE TITLE
My carelessness

### ISSUE THREAD

**Issue by jdleung** [vincentneo/CoreGPX#7]
Since in your installation guidance says: 

> CoreGPX will be available through CocoaPods. To install it, simply add the following line to your Podfile:
> 
> pod 'CoreGPX'

I did. But there were errors when build the project. I had to spend an hour to search solutions, and failed.

Finally, I found a line on the sample project:

> import CoreGPX

So far, parse GPX file is working fine but there is no instruction on output GPX file.

Can give sample codes?

Thanks.

**Comment by jdleung** [comment]
I got some sample code in other similar framework, problem solved but some code need to be modified so that it could output correctly.

**Comment by vincentneo** [comment]
@jdleung indeed, I will have to do up some instructions in the near future. As currently, the priority for this project is to optimise the parsing method for GPX files, as it is currently very slow.

Currently, should you have any enquiries, feel free to drop me a issue!

**Comment by jdleung** [comment]
By now I only use GPX file output function in my APP, it will be great if this part is optimized. 

I now use the following code to output ( it works but just don't know if it's the best way):
```
     let gpx = GPXRoot(creator: "MyRoute")
        let seg = GPXTrackSegment()
        for r in route.locations{
            let wp = GPXWaypoint(latitude: r.coordinate.latitude, longitude: r.coordinate.longitude, time:r.timestamp)
            wp.time = r.timestamp
            gpx.add(waypoint: wp)
            
            let trackPoint = GPXTrackPoint(latitude: r.coordinate.latitude, longitude: r.coordinate.longitude, time: r.timestamp)
            seg.add(trackpoint: trackPoint)            
        }
        
        let track = GPXTrack()
        track.name = "track name"
        track.desc = "track desc"
        track.add(trackSegment: seg)
        gpx.add(track: track)        
        let str = gpx.gpx()
```

**Comment by vincentneo** [comment]
I've seen your code, and may I ask why the initialisers for GPXWaypoint and GPXTrackPoint have an additional 'time' parameter? has the code been edited or has an extension?

**Comment by jdleung** [comment]
Yes, I read the GPX file format, it does has a timestamp for waypoint, it also fits my need, so I add it.
