### ISSUE TITLE
Can't get extensions from file

### ISSUE THREAD

**Issue by jearle1974** [vincentneo/CoreGPX#71]
Hey Vincentneo, I am trying to pull extensions from a file exported by basecamp but it is showing nothing. Am I doing something wrong? I tried finding some more documentation or examples but never had much luck.

Here is the GPX file

![Screen Shot 2020-03-05 at 11 08 28 AM](https://user-images.githubusercontent.com/56170634/75992630-d0f3c080-5ed2-11ea-9c01-cf5be5a2ae37.png)

and here is where the code seems to pull nothing, gpu.extensions showing nil

![Screen Shot 2020-03-05 at 11 20 08 AM](https://user-images.githubusercontent.com/56170634/75992929-4e1f3580-5ed3-11ea-9c32-e9e05d0f2c47.png)

Any help would be greatly appreciated.

**Comment by jearle1974** [comment]
Sorry Vincentneo, my bad, I was able to get the extension TrackExtension after, I didn't realize it was under track, I was trying to receive from Root. 

However, once I load the TrackExtension it says it has 0 children? Any ideas

**Comment by vincentneo** [comment]
Hi @jearle1974 
It does look like a possible bug based on my testing. Let me devise a fix. Thanks for reporting about the bug!

**Comment by vincentneo** [comment]
Pull Request #72 should fix. Do try it out!

**Comment by jearle1974** [comment]
Working great, thank you!
