### ISSUE TITLE
Are routepoints parsed?

### ISSUE THREAD

**Issue by Zakalicious** [vincentneo/CoreGPX#73]
I can import waypoints, trackpoints, but not routepoints. Is this feature not implemented?

Reading a valid gpx file with one route and 46 routepoints GPXParser(withURL: fileURL)?.parsedData() shows one route and zero routepoints.

Thanks.

**Comment by vincentneo** [comment]
Hey @Zakalicious ,

Thanks for opening this issue. I've just checked my implementation, and clumsy me, actually forgot to implement it for the route points! I wouldn't have noticed it if not for this issue. 
Will open a pull request real soon!
