### ISSUE TITLE
GPXParser forceContinue not working, spelling mistake.

### ISSUE THREAD

**Issue by georgbachmann** [vincentneo/CoreGPX#79]
I just got a gpx file that wasn't able to be parsed using CoreGPX. Turns out that there is a tag called `name` in there, that will make the parser fail. (`GPXError.parser.fileDoesNotConformSchema`)
I would suggest the parser to simply ignore that field?!?

Here's a short version from that gpx file
```
<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1">
<name>Workout</name>
<trk>
 <trkseg>
  <trkpt lat="48.8093302984832" lon="14.804627612153123">
   <ele>122.20398712158203</ele>
   <time>2020-06-04T11:16:19Z</time>
  </trkpt>
  <trkpt lat="48.80938393943352" lon="14.804649622856427">
   <ele>122.23384857177734</ele>
   <time>2020-06-04T11:16:20Z</time>
  </trkpt>
  <trkpt lat="48.80943728278103" lon="14.8046701043036">
   <ele>122.25633239746094</ele>
   <time>2020-06-04T11:16:21Z</time>
  </trkpt>
 </trkseg>
</trk>
</gpx>
```

**Comment by vincentneo** [comment]
Hi @georgbachmann,

I assume that you are using `.failibleParsedData(forceContinue: false)`. 
For that, it is designed to be restrictive.

If you wanted to parse without caring if the gpx file contained additional tags, use `.parsedData()` instead. It will provide you a parsed `GPXRoot` that should contain all the data the wanted, minus the erroneous <name> tag.

I hope this helps, do reopen if problems persists.
By the way, thanks, I just noticed a spelling error in the method name (fallible ~> failible)

Sincerely,
Vincent

**Comment by georgbachmann** [comment]
Thanks for your help @vincentneo . But I am using it like this: `gpxParser.failibleParsedData(forceContinue: true)
But i'll switch and use the `parsedData()` instead! Thanks!

**Comment by vincentneo** [comment]
Alright!

By the way with your issue, it kinda seem to also flag out a mistake on my end upon further looking, as `forceContinue` is unimplemented... Oh well. Will reopen this issue as a reminder to myself to make it do what its suppose to do.

**Comment by vincentneo** [comment]
I actually forgot that `forceContinue` was meant for the `XMLParser` errors and not `GPXParser`, hence, I only changed the name and pushed.

Oh well, guess I would have to have better documentation next time.
