### ISSUE TITLE
Waypoint link property (GPXLink) should be an array

### ISSUE THREAD

**Issue by VilemKurz** [vincentneo/CoreGPX#85]
First of all, thank you for such a great lib. It is very useful.

According to [GPX 1.1 spec](http://www.topografix.com/GPX/1/1/) waypoint can have unlimited number of links. So, `GPXWaypoint` should have `var links: [GPXLink]?` instead of current `var link: GPXLink?`. Same applies to `GPXRoute` and `GPXTrack`. Would you find the time to fix this?

**Comment by vincentneo** [comment]
interesting. looks like I might have missed this. will attempt to fix this asap!

**Comment by vincentneo** [comment]
this should be fixed in #86. Once I validate this code, it will be merged.

Thanks for the heads up about this issue! Would not have known that I misread the schema :)
