### ISSUE TITLE
CoreGPX.modulemap not found again

### ISSUE THREAD

**Issue by jdleung** [vincentneo/CoreGPX#90]
I had reported `CoreGPX.modulemap not found` before, and fixed it by new version CocoaPods and Xcode.

Today such error came out again after I added `use_frameworks!` in Podfile. It works again when I remove `use_frameworks!`.

I have latest CocoaPods and Xcode installed.

**Comment by vincentneo** [comment]
seems to work fine from my end, tried with a new project, and I have always used `use_frameworks!` in any of my projects.

May I know more information about the issue? 
Are you targeting the cocoa pods version 0.8.2 or master branch?

**Comment by jdleung** [comment]
There was a line in **Other Swift Flags**
`-fmodule-map-file="${PODS_CONFIGURATION_BUILD_DIR}/CoreGPX/CoreGPX.modulemap"`

CoreGPX works with `use_frameworks!` after deleted the line.
Thanks.

**Comment by vincentneo** [comment]
To be honest, I have no ideas what went wrong, but I have a feeling its another CocoaPods quirk as it commonly happens
