### ISSUE TITLE
Swift Package not showing all files from the latest version

### ISSUE THREAD

**Issue by alpennec** [vincentneo/CoreGPX#91]
I'm trying to use the GPXWaypointProtocol but the file is missing when using SPM. I'm using the latest 0.8.2 release.
Also, it seems other files are missing like GPXLegacy.swift, GPXFix.swift, etc.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/2082662/112714142-45800f80-8ed9-11eb-88e5-aa9cf873dccb.png">

**Comment by vincentneo** [comment]
Apologies for forgetting to make a new release again... 

Have done so now, with release 0.9.0!

Thanks for sending this in! Hope you have a good time using CoreGPX.

**Comment by alpennec** [comment]
@vincentneo thanks. The latest version is names 1.0 but the release is 0.9.0. Maybe it could be better to sync both in the next release (better for Swift Package Manager where you specify a next major version).
